# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6ff7d2f9ffaebb43450c819d67a3d733328b00aac35f471b7b5929248423b20730d46b6901f5b0c2ed9652fe052cecc7c8568069a6253dcdf9b371302080188

test:
  secret_key_base: 950907280ac317ee46ed69a0995a0fa33dcbfbe6931b4229447dd99e5e5fc722313024c0796f2ea5d9dbd857df6a134afdcf338d8843e23e34e1ea708d33ae47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
